# pyproject.toml
[tool.black]
line-length = 88
target-version = ['py39', 'py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.ruff]
line-length = 88
select = ["E", "F", "I"]  # E & F for errors, I for import sorting
fixable = ["ALL"]
